version: '3.5'

services:
  pg-bookstore-jpa:
    container_name: pg-bookstore-jpa
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookstore-jpa